/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.blackbaud.pacazurekafka.domain;  
@SuppressWarnings("CPD-START")
@org.apache.avro.specific.AvroGenerated
public class topic extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"topic\",\"namespace\":\"com.blackbaud.pacazurekafka.domain\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public topic() {}

  /**
   * All-args constructor.
   */
  public topic(java.lang.CharSequence name) {
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /** Creates a new topic RecordBuilder */
  public static com.blackbaud.pacazurekafka.domain.topic.Builder newBuilder() {
    return new com.blackbaud.pacazurekafka.domain.topic.Builder();
  }
  
  /** Creates a new topic RecordBuilder by copying an existing Builder */
  public static com.blackbaud.pacazurekafka.domain.topic.Builder newBuilder(com.blackbaud.pacazurekafka.domain.topic.Builder other) {
    return new com.blackbaud.pacazurekafka.domain.topic.Builder(other);
  }
  
  /** Creates a new topic RecordBuilder by copying an existing topic instance */
  public static com.blackbaud.pacazurekafka.domain.topic.Builder newBuilder(com.blackbaud.pacazurekafka.domain.topic other) {
    return new com.blackbaud.pacazurekafka.domain.topic.Builder(other);
  }
  
  /**
   * RecordBuilder for topic instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<topic>
    implements org.apache.avro.data.RecordBuilder<topic> {

    private java.lang.CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(com.blackbaud.pacazurekafka.domain.topic.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.blackbaud.pacazurekafka.domain.topic.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing topic instance */
    private Builder(com.blackbaud.pacazurekafka.domain.topic other) {
            super(com.blackbaud.pacazurekafka.domain.topic.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.blackbaud.pacazurekafka.domain.topic.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.blackbaud.pacazurekafka.domain.topic.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public topic build() {
      try {
        topic record = new topic();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
